export const REGIOES_ADMINISTRATIVAS = [
  "Brasília (Plano Piloto)",
  "Águas Claras",
  "Taguatinga",
  "Guará",
  "Sudoeste/Octogonal",
  "Sobradinho",
  "Vicente Pires",
  "Samambaia",
  "Ceilândia",
  "Lago Sul",
  "Lago Norte",
  "Jardim Botânico",
  "Cruzeiro",
  "Arniqueira",
  "Gama",
  "Sia",
  "Planaltina",
  "Santa Maria",
  "Recanto das Emas",
  "Riacho Fundo I",
  "Riacho Fundo II",
  "Candangolândia",
  "Itapoã",
  "Paranoá",
  "Park Way",
  "São Sebastião",
  "SCIA/Estrutural",
  "Varjão",
  "Fercal",
  "Sol Nascente/Pôr do Sol",
  "Brazlândia",
  "Núcleo Bandeirante",
  "Sobradinho II",
  "Jardim Botânico II",
  "Outra / Entorno do DF"
].sort();
